[package]
name = "example-utils"
version = "0.1.0"
edition = "2024"
publish = false

[lib]

[dependencies]
shrinkwrap = { path = "../../shrinkwrap" }
serde = { version = "1.0", features = ["derive"] }
