[package]
name = "shrinkwrap"
version = "0.0.1"
edition = "2024"
description = "Automates the wrapping and merging of data-based structs with associated metadata and extra information"
categories = ["data-structures", "development-tools", "value-formatting"]
repository = "https://github.com/kylekingcdn/shrinkwrap-rs"
license = "MIT"

[lib]

[dependencies]
